FROM gradle:7.0.2-jdk16 as builder

WORKDIR /app

ADD . .

RUN gradle shadowJar

FROM openjdk:16-alpine

WORKDIR /app

COPY --from=builder /app/build/libs/url_shortner.jar url_shortner.jar
COPY --from=builder /app/.env .env

CMD java -jar url_shortner.jar