name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo "Hello, world!"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7
      - name: Build with Gradle
        run: gradle --parallel --build-cache -Dorg.gradle.daemon=false shadowJar
  api-quick-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7
      - name: Run quick tests
        run: gradle --parallel --no-rebuild -Dorg.gradle.daemon=false quickTest --info
  api-slow-test:
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: url-shortner-ci
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      DB_DRIVER: postgresql
      TEST_DB_DRIVER: postgresql
      TEST_DB_HOST: localhost
      TEST_DB_NAME: eroman-ci
      TEST_DB_USER: postgres
      TEST_DB_PASSWORD: 1234
      TEST_DB_PORT: 5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7
      - name: Run slow tests
        run: gradle --parallel --no-rebuild -Dorg.gradle.daemon=false slowTest --info
